services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      #- "5672:5672"
      - "15672:15672" #Admin console access
      - "15674:15674" #rabbit_web_stomp
      - "61613:61613" # STOMP
      #- "1883:1883" #MQTT
    command:
      - /bin/bash
      - -c
      - |
        rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_stomp rabbitmq_web_stomp rabbitmq_mqtt
        rabbitmq-server
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password